name: Pog remote repository build

on:
  push:
    # this is also triggered when a PR is merged into main
    branches: ["main"]

# Grant GITHUB_TOKEN the permissions required to make a Pages deployment
permissions:
  pages: write      # to deploy to Pages
  id-token: write   # to verify the deployment originates from an appropriate source

jobs:
  github-pages:
    runs-on: windows-latest
    steps:
      - name: Configure git to preserve line endings
        run: git config --global core.autocrlf false

      - uses: actions/checkout@v4

      - name: Install Pog
        run: pwsh -noprofile .github\install-pog.ps1 D:\Pog

      - name: Validate local repository
        shell: pwsh
        run: |
          Import-Module Pog
          # use the local repository, instead of the default remote repo
          Set-PogRepository .

          # allow missing hashes, since some upstream projects do not version their releases,
          #  making it impossible to check for a fixed hash
          if (-not (Confirm-PogRepository -IgnoreMissingHash)) {
            throw "Repository validation failed (see warnings above)."
          }

      - name: Build remote repository
        run: pwsh -noprofile .github\build-remote-repo.ps1 D:\remote-repo .

      - uses: actions/upload-pages-artifact@v3
        with:
          path: D:\remote-repo

      - uses: actions/deploy-pages@v4
