name: Pog remote repository build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Grant GITHUB_TOKEN the permissions required to make a Pages deployment
permissions:
  pages: write      # to deploy to Pages
  id-token: write   # to verify the deployment originates from an appropriate source

jobs:
  github-pages:
    runs-on: windows-latest
    steps:
      - name: Configure git to preserve line endings
        run: git config --global core.autocrlf false

      - uses: actions/checkout@v4

      - name: Install Pog
        run: pwsh -noprofile .github\install-pog.ps1 D:\Pog

      - name: Build remote repository
        run: pwsh -noprofile .github\build-remote-repo.ps1 D:\remote-repo .

      - uses: actions/upload-pages-artifact@v3
        with:
          path: D:\remote-repo

      - uses: actions/deploy-pages@v4
